import {Shop, GoodsItem} from './types'
// 购物车数据
export const shopCartData = [
  new Shop('珀莱雅官方旗舰店', '1', [
    new GoodsItem(
      '1',
      '珀莱雅官方旗舰店',
      '1',
      '华为（HUAWEI）Mate60 Pro 旗舰手机 12GB+512GB 雅丹黑',
      703,
      '已售:100+',
      '12G+256G',
      '上海市徐汇区',
      2,
      'ic_home_6_1.png',
      true
    ),
    new GoodsItem(
      '1',
      '珀莱雅官方旗舰店',
      '3',
      'Appleipadpro 2022款苹果平板电脑 未使用 海外版 22款ipad pro11寸 灰色 256G WiFi版 未使用 店保一年',
      400.00,
      '已售:300+',
      '22款ipad pro 11寸 灰色',
      '上海市徐汇区',
      1,
      'ic_home_6_3.png',
      true
    ),
  ]),
  new Shop('山西汾酒官方旗舰店', '2', [
    new GoodsItem(
      '2',
      '山西汾酒官方旗舰店',
      '2',
      '汾酒 红盖玻汾 清香型白酒 42度 475mL 6瓶 整箱装',
      200.10,
      '已售:200+',
      '6瓶',
      '上海市徐汇区',
      1,
      'ic_home_6_2.png',
      true
    )
  ])
]

export const shopCartData2 = [
  new GoodsItem(
    '1',
    '珀莱雅官方旗舰店',
    '1',
    '华为（HUAWEI）Mate60 Pro 旗舰手机 12GB+512GB 雅丹黑',
    703,
    '已售:100+',
    '12G+256G',
    '上海市徐汇区',
    2,
    'ic_home_6_1.png',
    true
  ),
  new GoodsItem(
    '1',
    '珀莱雅官方旗舰店',
    '3',
    'Appleipadpro 2022款苹果平板电脑 未使用 海外版 22款ipad pro11寸 灰色 256G WiFi版 未使用 店保一年',
    400.00,
    '已售:300+',
    '22款ipad pro 11寸 灰色',
    '上海市徐汇区',
    1,
    'ic_home_6_3.png',
    true
  ),
  new GoodsItem(
    '2',
    '山西汾酒官方旗舰店',
    '2',
    '汾酒 红盖玻汾 清香型白酒 42度 475mL 6瓶 整箱装',
    200.10,
    '已售:200+',
    '6瓶',
    '上海市徐汇区',
    1,
    'ic_home_6_2.png',
    true
  ),
  new GoodsItem(
    '2',
    '山西汾酒官方旗舰店',
    '8',
    '运动鞋',
    1200.10,
    '已售:200+',
    '6瓶',
    '上海市徐汇区',
    1,
    'ic_home_6_2.png',
    true
  ),
  new GoodsItem(
    '2',
    '山西汾酒官方旗舰店',
    '9',
    '牛仔库',
    900.10,
    '已售:200+',
    '6瓶',
    '上海市徐汇区',
    1,
    'ic_home_6_2.png',
    true
  )
]